### ISSUE TITLE
Fasta download for expeditions containing photos fails

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-db#31]
Testing for the BOEM project, query an expedition.

pick an expedition containing photos and run query.   Then attempt to download FASTA data for that expedition and Server Error comes back.  Note that if we perform the same query for an expedition without photos, then the Server Error does not come back and completes OK. 

Following is stack trace when querying expedition with photos:

```
2020-03-13 14:31:32,568 INFO  (qtp1241276575-17) [PostgresRecordRepository(query:372)] ParametrizedQuery{sql='SELECT fastaSequence.data AS "fastaSequence_data", fastaSequence_entity_identifiers.identifier AS "fastaSequence_rootIdentifier", expeditions.expedition_code AS "expeditionCode", expeditions.project_id AS "projectId", Sample.data AS "Sample_data", Sample_entity_identifiers.identifier AS "Sample_rootIdentifier", Event.data AS "Event_data", Event_entity_identifiers.identifier AS "Event_rootIdentifier", Tissue.data AS "Tissue_data", Tissue_entity_identifiers.identifier AS "Tissue_rootIdentifier", Sample_Photo.data AS "Sample_Photo_data", Sample_Photo_entity_identifiers.identifier AS "Sample_Photo_rootIdentifier", Event_Photo.data AS "Event_Photo_data", Event_Photo_entity_identifiers.identifier AS "Event_Photo_rootIdentifier" FROM network_1.fastaSequence AS fastaSequence JOIN expeditions ON expeditions.id = fastaSequence.expedition_id JOIN network_1.Tissue AS Tissue ON Tissue.local_identifier = fastaSequence.parent_identifier and Tissue.expedition_id = fastaSequence.expedition_id JOIN network_1.Sample AS Sample ON Sample.local_identifier = Tissue.parent_identifier and Sample.expedition_id = Tissue.expedition_id JOIN network_1.Event AS Event ON Event.local_identifier = Sample.parent_identifier and Event.expedition_id = Sample.expedition_id LEFT JOIN network_1.Sample_Photo AS Sample_Photo ON Sample_Photo.parent_identifier = Sample.local_identifier and Sample_Photo.expedition_id = Sample.expedition_id LEFT JOIN network_1.Event_Photo AS Event_Photo ON Event_Photo.parent_identifier = Event.local_identifier and Event_Photo.expedition_id = Event.expedition_id LEFT JOIN entity_identifiers AS fastaSequence_entity_identifiers ON fastaSequence_entity_identifiers.expedition_id = fastaSequence.expedition_id and fastaSequence_entity_identifiers.concept_alias = 'fastaSequence' LEFT JOIN entity_identifiers AS Sample_entity_identifiers ON Sample_entity_identifiers.expedition_id = Sample.expedition_id and Sample_entity_identifiers.concept_alias = 'Sample' LEFT JOIN entity_identifiers AS Event_entity_identifiers ON Event_entity_identifiers.expedition_id = Event.expedition_id and Event_entity_identifiers.concept_alias = 'Event' LEFT JOIN entity_identifiers AS Tissue_entity_identifiers ON Tissue_entity_identifiers.expedition_id = Tissue.expedition_id and Tissue_entity_identifiers.concept_alias = 'Tissue' LEFT JOIN entity_identifiers AS Sample_Photo_entity_identifiers ON Sample_Photo_entity_identifiers.expedition_id = Sample_Photo.expedition_id and Sample_Photo_entity_identifiers.concept_alias = 'Sample_Photo' LEFT JOIN entity_identifiers AS Event_Photo_entity_identifiers ON Event_Photo_entity_identifiers.expedition_id = Event_Photo.expedition_id and Event_Photo_entity_identifiers.concept_alias = 'Event_Photo' WHERE expeditions.project_id = :1 AND expeditions.expedition_code = :2 ORDER BY fastaSequence.local_identifier, fastaSequence.expedition_id', params={1=44, 2=OIMB_2019_ARMS}}
2020-03-13 14:31:32,671 ERROR (qtp1241276575-17) [FimsExceptionMapper(logException:81)] class java.lang.NullPointerException thrown.
java.lang.NullPointerException
	at biocode.fims.records.RecordJoiner.joinRecords(RecordJoiner.java:64)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at biocode.fims.rest.services.subResources.QueryController.queryFasta(QueryController.java:350)
	at biocode.fims.rest.services.subResources.QueryController$$FastClassBySpringCGLIB$$b27fd79d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97)
	at biocode.fims.rest.versioning.VersionTransformer.transformResource(VersionTransformer.java:60)
	at jdk.internal.reflect.GeneratedMethodAccessor4083.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at biocode.fims.rest.services.subResources.QueryController$$EnhancerBySpringCGLIB$$bed52b51.queryFasta(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor4206.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:409)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:584)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at biocode.fims.rest.filters.ClickJackFilter.doFilter(ClickJackFilter.java:28)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ewingrj** [comment]
fixed in 127831f1584e53ae64ba27da4eb721fd1d6b9791
