### ISSUE TITLE
strict ooxml format in xlsx spreadsheet returns generic error

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-db#33]
i'm not sure we can fix not being able to take strict ooxml format sheets due to Apache POI bug.  (though we should check the bug referenced below to see if it is fixed).  We should, however, return a more informative message to the user, rather than "server error".

```
java.util.concurrent.CompletionException: org.apache.poi.ooxml.POIXMLException: Strict OOXML isn't currently supported, please see bug #57699
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.poi.ooxml.POIXMLException: Strict OOXML isn't currently supported, please see bug #57699
    at org.apache.poi.ooxml.POIXMLDocumentPart.getPartFromOPCPackage(POIXMLDocumentPart.java:741)
    at org.apache.poi.ooxml.POIXMLDocumentPart.<init>(POIXMLDocumentPart.java:147)
    at org.apache.poi.ooxml.POIXMLDocumentPart.<init>(POIXMLDocumentPart.java:137)
    at org.apache.poi.ooxml.POIXMLDocument.<init>(POIXMLDocument.java:61)
    at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:280)
    at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:83)
    at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:111)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:314)
    at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:296)
    at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:284)
    at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:253)
    at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:234)
    at biocode.fims.reader.plugins.ExcelReader.init(ExcelReader.java:72)
    at biocode.fims.reader.plugins.AbstractTabularDataReader.getRecordSets(AbstractTabularDataReader.java:52)
    at biocode.fims.reader.plugins.ExcelReader.getRecordSets(ExcelReader.java:37)
    at biocode.fims.run.DatasetBuilder.readData(DatasetBuilder.java:158)
    at biocode.fims.run.DatasetBuilder.instantiateWorkbookRecords(DatasetBuilder.java:150)
    at biocode.fims.run.DatasetBuilder.build(DatasetBuilder.java:125)
    at biocode.fims.run.DatasetProcessor.validate(DatasetProcessor.java:98)
    at biocode.fims.rest.services.DatasetController.lambda$validate$0(DatasetController.java:220)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    ... 1 more
```

**Comment by jdeck88** [comment]
[FuTRES_Puma_concolor_ODFW_OR_USA_Modern (1).xlsx](https://github.com/biocodellc/geome-db/files/4804909/FuTRES_Puma_concolor_ODFW_OR_USA_Modern.1.xlsx)
Here is a file to test with saved in OOXML format for Futres project

**Comment by jdeck88** [comment]
has not been an issue in 5 years... closing
